apiVersion: apps/v1
kind: Deployment
metadata:
  name: iss-tracker-deployment
  labels:
    app: iss-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iss-tracker
  template:
    metadata:
      labels:
        app: iss-tracker
    spec:
      containers:
      - name: iss-tracker-app
        volumeMounts:
          - name: db-mount
            mountPath: /db-mount/
        image: k3d-registry:5000/iss-app:latest
      # imagePullSecrets:
      # - name: regcred
    
      - name: iss-tracker-db
        volumeMounts:
          - name: db-mount
            mountPath: /db-mount/
        image: k3d-registry:5000/iss-db:latest
      # imagePullSecrets:
      # - name: regcred

      volumes:
      - name: db-mount
        emptyDir: {}