apiVersion: v1
kind: Pod
metadata:
  name: iss-tracker
  labels:
    app: iss-tracker
spec:
    containers:
    - name: iss-tracker-app
      volumeMounts:
        - name: db-mount
          mountPath: /db-mount/
      image: jacksonnewlands/iss-tracker-app:working
    imagePullSecrets:
    - name: regcred
  
    - name: iss-tracker-db
      volumeMounts:
        - name: db-mount
          mountPath: /db-mount/
      image: jacksonnewlands/iss-tracker-db:working
    imagePullSecrets:
    - name: regcred

    volumes:
    - name: db-mount
      emptyDir: {}